/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Reset for +": "重置获得 +",
    "The Beginning of a Journey": "旅程的开始",
    "Achievement Gotten!": "成就达成！",
    "Currently": "当前",
    "Double point gain per L1 upgrade bought.": "每购买一次 L1 升级则获得双倍点数。",
    "Doubler": "加倍",
    "Each layer resets the ones before it.": "每一层都会重置它之前的层。",
    "Extra Points": "额外点数",
    "Gain more points based on L1 points.": "基于L1点获得更多点数。",
    "I am a button!": "我是一个按钮！",
    "Modes": "模式",
    "Layer Info": "层信息",
    "points": " 点数",
    "Autobuy upgrades, gain 3x more of each layer's currency, and keep L4 upgrades on middle reset.": "自动购买升级，每层获得 3 倍以上的货币，并在中间重置时保留 L4 升级。",
    "Grindless": "不受约束",
    "achievements.": "成就.",
    "Half Way There!": "到一半了!",
    "Strategy Acquired": "战略获得",
    "Layer Up!": "层层叠叠！",
    "There's more of them?": "还有更多吗？",
    "What about the last one?": "最后一个怎么样？",
    "Where's the QoL?": "QoL 在哪里？",
    "You have completed": "你已经完成了",
    "Even More Points": "更多点数",
    "Extra Upgrades": "额外升级",
    "Gain more points based on L2 points.": "基于 L2点 获得更多点数。",
    "Corner resets don't reset anything.": "角落重置不会重置任何东西。",
    "Increase": "提高",
    "Keep all keeper upgrades on layer, corner, and line reset.": "保留层、角和线重置的所有 保留者 升级。",
    "Multiply L1 point gain based on the amount of L1 upgrades you have.": "根据您拥有的 L1 升级数量乘以 L1 点增益。",
    "Past Doubler": "过去倍增器",
    "'s base by L2 upgrades.": "的基础由 L2 升级。",
    "You can buy max CP.": "您可以购买最大CP。",
    "Upgrades": "升级",
    "Unlock extra nerfs for The": "解锁额外的 神经 为",
    "Unlock": "解锁",
    "Unlock challenges and change the effect of": "解锁挑战并改变效果",
    "The Prestige Triangle": "声望三角",
    "The Challenge": "挑战",
    "Speed Up": "提速",
    "Start with 1 CP per 2 line milestones.": "从每 2 行里程碑 1 CP 开始。",
    "Selector": "选择器",
    "Reset All": "重置所有",
    "Red": "红色",
    "QoL, while helpful, isn't required.": "QoL 虽然有帮助，但不是必需的。",
    "Point Exponent": "点数指数",
    "Point Boosters+": "点数助推器+",
    "Point Boosters": "点数助推器",
    "Layers": "层",
    "lines": "行",
    "Main": "主要",
    "Improve": "改进",
    "Improve+": "改进+",
    "Now What?": "现在怎么办?",
    "Hint": "提示",
    "Help": "帮助",
    "green": "绿色",
    "Finish": "完成",
    "Extra Nerfs": "额外神经",
    "Extra L3": "额外L3",
    "Energy": "能量",
    "Exit Early": "提前退出",
    "Goal:": "目标:",
    "Reward": "奖励",
    " points": " 点数",
    "'s base by 0.005 for each one you buy.": "您购买的每件商品以 0.005 为基数。",
    "'s cost by the amount you have.": "的成本按您拥有的金额计算。",
    "Boost point gain based on total lines and CP.": "基于总行数和CP的提升点增益。",
    "Challenge": "挑战",
    "Challenges": "挑战",
    "Challenge Goal": "挑战目标",
    "Challenge Info": "挑战信息",
    "Completed": "已完成",
    "corner points": "角落点数",
    "DE Boost": "DE 提升",
    "DE Multiplier": "DE 乘数",
    "DE to Points": "DE 到 点数",
    "Divide": "分隔",
    "Dividers": "分隔线",
    "Doubler Update": "双重更新",
    "Yet Another Layer": "还有一层",
    "You can bulk complete": "您可以批量完成",
    "Upgrade": "升级",
    "Unlock The Prestige Triangle.": "解锁声望三角。",
    "Unlock The Challenge.": "解锁挑战。",
    "Unlock downgrade energy.": "解锁降级能量。",
    "Ultra Points": "终极点",
    "The Middle": "中间",
    "Square": "方形",
    "Reach 1.79e308 points within The Challenge with only Point Boosters enabled.": "仅启用点数助推器，在挑战赛中达到 1.79e308 点数。",
    "Reach 1.79e308 points within The Challenge with Doubler disabled.": "在禁用倍频器的挑战中达到 1.79e308 点数。",
    "Reach 1.79e308 points within The Challenge with all the upgrades that unlock new upgrades disabled.": "在挑战中达到 1.79e308 点，同时禁用所有解锁新升级的升级。",
    "Passively gain L2 points and keep 1 L4 upgrade per milestone.": "被动获得 L2 点数并保留每个里程碑 1 次 L4 升级。",
    "Passively gain L1 points and double point gain.": "被动获得L1点数和双倍点数。",
    "Maxed Out": "爆棚",
    "Lossless Corners": "无损转角",
    "Loss of a corner": "失一角",
    "Loss": "缺失",
    "L1 is deactivated and passive generation is removed but L2 requires points and some upgrades are changed.": "L1 被停用，被动生成被移除，但 L2 需要点数并且一些升级被更改。",
    "It's not like I needed those upgrades anyway": "反正我不需要那些升级",
    "Imagine using Doublers": "想象一下使用倍增器",
    "Getting OP": "获得 OP",
    "Get the second line milestone.": "获取第二行里程碑。",
    "Get 50 L3 points.": "Get 50 L3 点数.",
    "Gain 10x more points and raise": "获得 10 倍以上的点数并提高",
    "Gain 100x more of all layer points per CP and passively gain L3 points.": "每个 CP 获得 100 倍以上的所有层点数并被动获得 L3 点数。",
    "Finish The Prestige Triangle 5 times.": "完成声望三角 5 次。",
    "Finish The Challenge.": "Finish The Challenge.",
    "Finally More Upgrades": "最后更多升级",
    "Extreme Downgrades": "极限降级",
    "Even More Qol!": "甚至更多的 Qol！",
    "Even More Points!": "甚至更多的点数！",
    "Energize!": "加油！",
    "effect.": "效果.",
    "effect": "效果",
    "Creating Lines": "创建线",
    "Complete": "完成",
    "Buy More DE to Points.": "购买更多 DE 到点数。",
    "Buy DE to Points.": "购买 DE 到点数。",
    "But there's no point...": "但是没有点数...",
    "Boost point gain based on point amount.": "根据点数增加点数。",
    "Be able to gain 2 lines in one line reset.": "一次线路复位即可获得2条线路。",
    "Actually Qol!?": "真的Qol！？",
    "Actually 2?": "实际上2？",
    "A New Challenge?": "新挑战？   ",
    "A few MP later...": "一些MP之后...",
    "Congratulations! You have reached the end and wasted your time.": "恭喜！ 你已经走到了尽头，浪费了你的时间。",
    "If you don't know how to get enough DP to progress you can read these hints.": "如果你不知道如何获得足够的 DP 来进步，你可以阅读这些提示。",
    "Info": "信息",
    "is better based on CP.": "基于CP更好。",
    "is better based on DE.": "基于DE更好。",
    "is better based on DP.": "基于DP更好。",
    "is better based on DP and double DE gain.": "基于DP更好和双倍DE增益。",
    "Keep passive L2 gain in": "保留被动 L2 增益",
    "L3 upgrades aren't as good as you might think.": "L3 升级并不像您想象的那么好。",
    "Lose upgrades of your choice.": "失去您选择的升级。",
    "Max Prestige Triangle Completions": "最大声望三角完成",
    "means it isn't. You get more DP from better upgrades.": "意味着它不是。 您从更好的升级中获得更多 DP。",
    "means it's deactivated for the challenge while": "意味着它已为挑战而停用，而",
    "More DE to Points": "更多 DE 到点数",
    "Passively gain L4 points.": "被动获得L4点数。",
    "Ultra Doubler": "终极倍增器",
    "Gain more points based on DE.": "基于DE获得更多点数。",
    "Gain more DE based on DP.": "基于 DP 获得更多 DE。",
    "Gain more DE based on DE upgrades bought.": "根据购买的 DE 升级获得更多 DE。",
    "Gain DE 5x faster.": "获得 DE 速度提高 5 倍。",
    "Gain 2.250x more DE per purchase.": "每次购买多获得 2.250x DE。",
    "DP milestones affect line milestone 2 in a normal run.": "DP 里程碑影响正常运行中的线路里程碑 2。",
    "Final L1": "最终L1",
    "DP generates downgrade energy.": "DP 产生降级能量。",
    "Doubler 2.1": "倍增器 2.1",
    "and": "和",
    "10 max completions": "最多 10 次完成",
    "'s effect.": "的效果。",
    "Buy & Reset": "购买 & 重置",
    "Extra Upgrades+": "额外升级+",
    "Other Layer Boosting": "其他层提升",
    "So Many Points": "这么多点数",
    "Ultimate Doubler": "终极倍增器",
    "What?": "啥？",
    "to 1.2.": "到 1.2.",
    "L3 to L1": "L3 到 L1",
    "Keep L3 upgrades on reset and unlock 2 L2 upgrades.": "重置时保留 L3 升级并解锁 2 个 L2 升级。",
    "Start": "开始",
    "Testers": "测试人员",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Keeper ": "保留者 ",
    "\t\t\t\t": "\t\t\t\t",
    "Completions: ": "完成: ",
    "Get Keeper ": "获取 保留者",
    "Get Final L": "获得最终 L",
    "Effect: ": "效果: ",
    "DP: ": "DP: ",
    "DP on challenge completion: ": "完成挑战的DP：",
    "Amount: ": "数量: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) DP$/,
    /^([\d\.]+) CP$/,
    /^([\d\.]+) DE$/,
    /^([\d\.]+)s$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Get (.+) downgrade energy.$/, '获得 $1 降级能量.'],
    [/^Get (.+) upgrades.$/, '获得 $1 升级.'],
    [/^gain (.+) DP$/, '获得 $1DP'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分 $2秒'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1小时 $2分 $3秒'],
    [/^Get ([\d\.,]+) line.$/, '获得 $1 线.'],
    [/^Get ([\d\.,]+) MP.$/, '获得 $1 MP.'],
    [/^Keep L(.+) upgrades on reset.$/, '在重置时保留 L$1 升级。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You have (.+) downgrade points.$/, '您有 $1 降级点数。'],
    [/^You have (.+) downgrade energy \(\+(.+)$/, '你有 $1 降级能量 \(\+$2'],
    [/^You have earned (.+) lines in total.$/, '您总共获得了 $1 行。'],
    [/^You are gaining (.+) L(.+) points per second$/, '你每秒获得 $1 L$2 点数'],
    [/^Req: (.+) \/ (.+) points$/, '需要: $1 \/ $2 点数'],
	[/^Autobuy L([\d\.]+) upgrades.$/, '自动购买 L$1 升级。'],
	[/^([\d\.]+) Line$/, '$1 行'],
	[/^\spoints$/, ' 点数'],
	[/^([\d\.]+) Lines$/, '$1 行'],
	[/^([\d\.]+) Total Lines$/, '$1 总行数'],
	[/^([\d\.]+) corner points$/, '$1 角落点数'],
	[/^([\d\.]+)x DP$/, '$1x DP'],
	[/^L([\d\.]+) Boosting$/, 'L$1 提升'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
	[/^([\d\.]+)e([\d\.,]+) OOMs\/sec$/, '$1e$2 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
	[/^([\d\.]+) L([\d\.]+) points$/, '$1 L$2 点数'],
	[/^([\d\.,]+) L([\d\.]+) points$/, '$1 L$2 点数'],
	[/^([\d\.]+)e([\d\.,]+) L([\d\.]+) points$/, '$1e$2 L$3 点数'],
	[/^([\d\.]+) lines$/, '$1 线'],
	[/^([\d\.]+): Reset for L([\d\.]+) points$/, '$1：重置获得 L$2 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^L([\d\.]+) points$/, 'L$1 点数'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Reach (.+) points to unlock \(You have (.+) points$/, '达到 $1 点解锁（你有 $2 点'],
    [/^Unlock (.+) L(.+) upgrades.$/, '解锁 $1 L$2 升级.'],
    [/^Buy (.+) L(.+) upgrades.$/, '购买 $1 L$2 升级.'],
    [/^Get (.+) L(.+) point.$/, '获得 $1 L$2 点。'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) DE$/, '成本：$1 DE'],
    [/^Cost: (.+) lines$/, '成本：$1 线'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);